global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

storage:
  exemplars:
    max_exemplars: 100000

alerting:

scrape_configs:
  - job_name: "kronk"
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: [ "host.docker.internal:8090" ]
